<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["answers", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit answers
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "answers/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldQuestId" class="col-sm-2 control-label">Quest(id вопроса)</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["quest_id", "type" => "number", "class" => "form-control", "id" => "fieldQuestId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldGood" class="col-sm-2 control-label">Good(1/0)</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["good", "type" => "number", "class" => "form-control", "id" => "fieldGood"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
