<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Поиск ответа
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["/", "На главную"]) ?>
        <?php echo $this->tag->linkTo(["answers/new", "Create answers"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "answers/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldQuestId" class="col-sm-2 control-label">Quest(id вопроса)</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["quest_id", "type" => "number", "class" => "form-control", "id" => "fieldQuestId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldGood" class="col-sm-2 control-label">Good(1/0)</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["good", "type" => "number", "class" => "form-control", "id" => "fieldGood"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
